<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

namespace Sample;

use UnexpectedValueException;

/**
 * Protobuf type <code>sample.Role</code>
 */
class Role
{
    /**
     * Generated from protobuf enum <code>GUEST = 0;</code>
     */
    const GUEST = 0;
    /**
     * Generated from protobuf enum <code>MEMBER = 1;</code>
     */
    const MEMBER = 1;
    /**
     * Generated from protobuf enum <code>ADMIN = 2;</code>
     */
    const ADMIN = 2;

    private static $valueToName = [
        self::GUEST => 'GUEST',
        self::MEMBER => 'MEMBER',
        self::ADMIN => 'ADMIN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

