<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

namespace GrpcServices\Sample\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>sample.ListUsersRequest</code>
 */
class ListUsersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Only list users created after this timestamp
     *
     * Generated from protobuf field <code>string created = 1;</code>
     */
    protected $created = '';
    /**
     * Only list users older than this Duration
     *
     * Generated from protobuf field <code>string older = 2;</code>
     */
    protected $older = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $created
     *           Only list users created after this timestamp
     *     @type string $older
     *           Only list users older than this Duration
     * }
     */
    public function __construct($data = NULL) {
        \GrpcServices\Sample\Sample::initOnce();
        parent::__construct($data);
    }

    /**
     * Only list users created after this timestamp
     *
     * Generated from protobuf field <code>string created = 1;</code>
     * @return string
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Only list users created after this timestamp
     *
     * Generated from protobuf field <code>string created = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkString($var, True);
        $this->created = $var;

        return $this;
    }

    /**
     * Only list users older than this Duration
     *
     * Generated from protobuf field <code>string older = 2;</code>
     * @return string
     */
    public function getOlder()
    {
        return $this->older;
    }

    /**
     * Only list users older than this Duration
     *
     * Generated from protobuf field <code>string older = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOlder($var)
    {
        GPBUtil::checkString($var, True);
        $this->older = $var;

        return $this;
    }

}

